version: "3.7"

networks:
  eodag-stac-network:
    driver: bridge

services:
  browser:
    build:
      context: .
      dockerfile: docker/stac-browser.dockerfile
    container_name: stac_browser
    restart: unless-stopped
    networks:
      - eodag-stac-network
    ports:
      - "5001:80"
  stac:
    build:
      context: .
      dockerfile: docker/stac-server.dockerfile
    environment:
      - "EODAG_LOGGING=${EODAG_LOGGING}"
      - "EODAG_CORS_ALLOWED_ORIGINS=https://54.89.201.212:446,https://waternode.ciroh.org:446"
    container_name: stac_server
    restart: unless-stopped
    networks:
      - eodag-stac-network
    ports:
      - "5000:5000"
