title: 'Water Prediction Node'
default_lang: en
author:
  name: 'Adam Warnock'
  email: akwarnock@ua.edu
taxonomies:
  - category
  - tag
metadata:
  description: 'A NOAA Coast Watch Node'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
